name: Tests

on:
  push:
  pull_request:
  repository_dispatch:
    types: manual-test-run

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"
          - "16"
          - "14"
        include:
          - node: "14"
            ENABLE_CODE_COVERAGE: true
    name: Run tests on NodeJS ${{ matrix.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload code coverage
        if: matrix.ENABLE_CODE_COVERAGE
        uses: codecov/codecov-action@v1
