name: Build Typst document

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.13.1
          cache-dependency-path: oi-wiki-export-typst/oi-wiki.typ

      - name: Pre-build operations
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get update
          sudo apt-get install curl git unzip imagemagick libwebp-dev librsvg2-dev fonts-noto-cjk fonts-noto-cjk-extra
          sudo apt-get remove fonts-noto-color-emoji
          
          mkdir .fonts
          curl -L $(gh api /repos/lxgw/LxgwWenKai/releases/latest -q '.assets[].browser_download_url | select(contains("tar.gz"))') | tar xfz - -C .fonts
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://github.com/google/fonts.git
          cd fonts
          git sparse-checkout add ofl/crimsontext
          git checkout
          cd ..
          cp -r fonts/* .fonts

          git clone https://github.com/OI-wiki/OI-wiki.git --depth=1 --single-branch -b master
          cd remark-snippet
          npm install
          cd ..
          cd remark-typst
          npm install
          cd ..
          cd oi-wiki-export-typst
          npm install

      - name: Build Typst document
        run: |
          cd oi-wiki-export-typst
          node index.js ../OI-wiki
          typst compile oi-wiki-export.typ --font-path ../.fonts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OI-wiki.pdf
          path: ./oi-wiki-export-typst/oi-wiki-export.pdf
