name: Build LaTeX document

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -8bit"
          extra_system_packages: |
            unzip
            wget
            curl
            coreutils
            nodejs
            npm
            imagemagick
            libwebp
            librsvg
            git
            py3-pygments
            inkscape
            libxml2
            font-noto-cjk
            font-noto-cjk-extra
            font-noto
          pre_compile: |
            wget "http://mirrors.ctan.org/fonts/cm-unicode.zip"
            wget -O robotomono.zip "https://fonts.google.com/download?family=Roboto%20Mono"
            unzip robotomono.zip -d robotomono
            unzip ./cm-unicode.zip
            cp -r robotomono cm-unicode/fonts/otf/* /usr/share/fonts
            fc-cache
            cd remark-latex
            npm i
            cd ..
            cd oi-wiki-export
            npm i
            git clone https://github.com/OI-wiki/OI-wiki.git
            node index.js ./OI-wiki

          root_file: |
            oi-wiki-export.tex
      - uses: actions/upload-artifact@v2
        with:
          name: OI-wiki.pdf
          path: ./oi-wiki-export/oi-wiki-export.pdf
