name: Build LaTeX document

on:
  push:
    branches:
      - master
  pull_request:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=batchmode -8bit"
          extra_system_packages: |
            unzip
            wget
            curl
            coreutils
            nodejs
            npm
            imagemagick
            libwebp
            librsvg
            git
            python3
            py3-pygments
            libxml2
            openssh
            sqlite-dev
          pre_compile: |
            umask 0 && npm config set cache /tmp/.npm
            wget -q -O notosans.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip"
            wget -q -O notoserif.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-hinted.zip"
            wget -q -O notoserifcjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKsc-hinted.zip"
            wget -q -O notosanscjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip"
            git clone https://github.com/googlefonts/RobotoMono
            curl -L -o cm-unicode.zip "https://mirrors.ctan.org/fonts/cm-unicode.zip"
            unzip -q notosans.zip -d notosans
            unzip -q notoserif.zip -d notoserif
            unzip -q notosanscjk.zip -d notosanscjk
            unzip -q notoserifcjk.zip -d notoserifcjk
            unzip -q ./cm-unicode.zip
            cp -r notosans notoserif notosanscjk notoserifcjk cm-unicode/fonts/otf/* RobotoMono/fonts/ttf/* /usr/share/fonts
            fc-cache
            cd remark-snippet
            npm i
            cd ..
            cd remark-latex
            npm i
            cd ..
            cd oi-wiki-export
            npm i
            git clone https://github.com/OI-wiki/OI-wiki.git --depth=1 --single-branch -b master
            python3 increase-mem-limit.py
            fmtutil-sys --all
            node index.js ./OI-wiki

          root_file: |
            oi-wiki-export.tex

      - name: Upload logs on failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: log
          path: ./oi-wiki-export/oi-wiki-export.log

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: OI-wiki.pdf
          path: ./oi-wiki-export/oi-wiki-export.pdf
